const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')
const test = require('node:test')

const root = join(__dirname, '..')
const newPage = readFileSync(join(root, 'src/pages/order/new.vue'), 'utf8')
const customerPicker = readFileSync(join(root, 'src/components/CustomerPicker.vue'), 'utf8')
const numberBox = readFileSync(
  join(root, 'src/uni_modules/uni-number-box/components/uni-number-box/uni-number-box.vue'),
  'utf8',
)
const tokens = readFileSync(join(root, 'src/uni.scss'), 'utf8')
const pages = JSON.parse(readFileSync(join(root, 'src/pages.json'), 'utf8'))
const design = readFileSync(join(root, 'docs/design.md'), 'utf8')

test('order new page keeps the real data chain and state machine', () => {
  assert.match(newPage, /useOrderStore\(\)/)
  assert.match(newPage, /useCustomerStore|CustomerPicker/)
  assert.match(newPage, /findEffectiveOrder/)
  assert.match(newPage, /getMealCardAvailability/)
  assert.match(newPage, /order_date:\s*tomorrow\(\)/)
  assert.match(newPage, /meal_type:\s*['"]lunch['"]/)
  assert.match(newPage, /payment_mode:\s*['"]wechat['"]/)
  assert.match(newPage, /quantity:\s*1/)
  assert.match(newPage, /usePageReturnSnapshot/)
  assert.match(newPage, /pageReturn\.restoreOnShow/)
  assert.match(newPage, /OrderPriceConfirmationError/)
  assert.match(newPage, /choosePostSaveAction/)
  assert.match(newPage, /继续下一单/)
  assert.match(newPage, /结束录单/)
  assert.match(newPage, /将合并到已有待配送订单/)
  assert.match(newPage, /查看已有订单/)
  assert.match(newPage, /这位客户这餐已经配送完成/)
  assert.match(newPage, /组合支付/)
  assert.match(newPage, /改为纯支付/)

  const demoValues = ['#128', '¥30.00']
  for (const demoValue of demoValues) {
    assert.doesNotMatch(newPage, new RegExp(demoValue.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  }
})

test('order new page visual contract uses warm paper semantic tokens', () => {
  assert.match(tokens, /\$hej-color-canvas:\s*#f5f4ed/i)
  assert.match(tokens, /\$hej-color-surface:\s*#faf9f5/i)
  assert.match(tokens, /\$hej-color-accent:\s*#c96442/i)
  assert.match(tokens, /\$hej-color-pending:\s*#657789/i)
  assert.match(newPage, /<style scoped lang="scss">/)
  assert.match(newPage, /\$hej-color-canvas/)
  assert.match(newPage, /\$hej-color-surface/)
  assert.match(newPage, /\$hej-color-accent/)
  assert.match(newPage, /\$hej-color-pending/)
  assert.match(newPage, /min-width:\s*200rpx/)
  assert.match(newPage, /height:\s*64rpx/)
  assert.doesNotMatch(newPage, /#0070f3/i)
  assert.doesNotMatch(customerPicker, /#007aff/i)
  assert.match(customerPicker, /<style scoped lang="scss">/)
  assert.match(customerPicker, /\$hej-color-accent/)
  assert.match(customerPicker, /getCustomerPinyinKey/)
  assert.match(customerPicker, /getCustomerPinyinInitials/)
  assert.match(customerPicker, /discountLabel/)
  assert.match(design, /暖纸张|warm-paper/i)
})

test('shared number box matches the portions stepper visual contract', () => {
  assert.match(numberBox, /<HejiIcon name="Minus"/)
  assert.match(numberBox, /<HejiIcon name="Plus"/)
  assert.match(numberBox, /width: 100%/)
  assert.match(numberBox, /height: 72rpx/)
  assert.match(numberBox, /border-radius: \$hej-radius-control/)
  assert.match(numberBox, /border-radius: 50%/)
  assert.match(numberBox, /uni-numbox--focused/)
  assert.match(numberBox, /uni-numbox-btns--disabled/)
  assert.match(numberBox, /v-model="inputValue"/)
  assert.match(numberBox, /this\.\$emit\("change"/)
  assert.doesNotMatch(newPage, /quantity-box :deep\(\.uni-numbox-btns\)/)
})

test('order new page retains sub-page navigation semantics in pages.json', () => {
  const newPageEntry = pages.pages.find((page) => page.path === 'pages/order/new')
  assert.ok(newPageEntry)
  assert.equal(newPageEntry.style?.navigationBarTitleText, '新建订单')
  assert.notEqual(newPageEntry.style?.navigationStyle, 'custom')
})
