import type { Component } from 'vue'
import {
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  Ban,
  Banknote,
  Bell,
  Bike,
  CalendarDays,
  ChartNoAxesColumn,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clipboard,
  ClipboardCopy,
  Clock3,
  CookingPot,
  Copy,
  DatabaseBackup,
  Download,
  Eye,
  EyeOff,
  FileCheck2,
  FilePenLine,
  FileText,
  FolderPlus,
  History,
  Info,
  Lightbulb,
  List,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  NotebookPen,
  Package,
  Pencil,
  Plus,
  ReceiptText,
  RefreshCw,
  Search,
  Send,
  ShoppingCart,
  SquarePen,
  Star,
  Sun,
  Ticket,
  Trash2,
  Upload,
  UserRound,
  UsersRound,
  Utensils,
  Wallet,
  Wrench,
  X,
} from '@lucide/vue'

export const HEJI_ICON_COMPONENTS = {
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  Ban,
  Banknote,
  Bell,
  Bike,
  CalendarDays,
  ChartNoAxesColumn,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clipboard,
  ClipboardCopy,
  Clock3,
  CookingPot,
  Copy,
  DatabaseBackup,
  Download,
  Eye,
  EyeOff,
  FileCheck2,
  FilePenLine,
  FileText,
  FolderPlus,
  History,
  Info,
  Lightbulb,
  List,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  NotebookPen,
  Package,
  Pencil,
  Plus,
  ReceiptText,
  RefreshCw,
  Search,
  Send,
  ShoppingCart,
  SquarePen,
  Star,
  Sun,
  Ticket,
  Trash2,
  Upload,
  UserRound,
  UsersRound,
  Utensils,
  Wallet,
  Wrench,
  X,
} satisfies Record<string, Component>

export type HejiIconName = keyof typeof HEJI_ICON_COMPONENTS

export type HejiIconNode = readonly [
  string,
  Readonly<Record<string, string | number | boolean | null | undefined>>,
][]

type LucideIconComponent = (
  props: Record<string, never>,
  context: { attrs: Record<string, never>; slots: Record<string, never> },
) => { props?: { iconNode?: HejiIconNode } }

function extractIconNode(component: Component): HejiIconNode {
  const renderIcon = component as unknown as LucideIconComponent
  return renderIcon({}, { attrs: {}, slots: {} }).props?.iconNode ?? []
}

/**
 * Lucide 的 SVG 组件在 Android app-plus WebView 中可能得到 0×0 布局且不绘制。
 * 保留同一份 Lucide 原始节点，供 HejiIcon 生成 CSS mask 数据 URI。
 */
export const HEJI_ICON_NODES = Object.fromEntries(
  Object.entries(HEJI_ICON_COMPONENTS).map(([name, component]) => [
    name,
    extractIconNode(component),
  ]),
) as { [Name in HejiIconName]: HejiIconNode }
